source 'git@bitbucket.org:cabosoft-mobile/cabopods-ios.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'graylogger_Example' do
  pod 'graylogger', :path => '../'

  target 'graylogger_Tests' do
    inherit! :search_paths
	pod 'graylogger', :path => '../'
	pod 'SwiftyJSON'
  end
  
end
