source 'git@bitbucket.org:cabosoft-mobile/cabopods-ios.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'graylogger_Example' do
	platform :ios, '10.0'
	pod 'graylogger', :path => '../'
	pod 'graylogger/CoreDataCache', :path => '../'
	pod 'graylogger/ReachabilitySwift', :path => '../'
	pod 'graylogger/AFNetworking', :path => '../'
	pod 'graylogger/Alamofire', :path => '../'
	pod 'graylogger/AnalyticsKit', :path => '../'
	
	pod 'AnalyticsKit/Core', :git => 'git@github.com:twobitlabs/AnalyticsKit.git'

  target 'graylogger_Tests' do
    inherit! :search_paths
	pod 'graylogger/CoreDataCache', :path => '../'
	pod 'SwiftyJSON'
  end
  
end

